#!/bin/bash
# 配置备份和验证快速指南

echo "======================================"
echo "配置备份和验证工具"
echo "======================================"
echo ""
echo "1. 备份配置到 JSON 文件"
echo "   python scripts/backup_configs.py"
echo ""
echo "2. 验证最新备份文件"
echo "   python scripts/verify_backup.py"
echo ""
echo "3. 验证指定表的备份"
echo "   python scripts/verify_backup.py --table sync_task_config"
echo ""
echo "4. 验证指定文件"
echo "   python scripts/verify_backup.py --file backups/sync_task_config_20260308_120000.json"
echo ""
echo "5. 恢复配置从备份"
echo "   python scripts/restore_configs.py"
echo ""
echo "6. 验证数据库表完整性"
echo "   python scripts/verify_integrity.py"
echo ""
echo "======================================"
echo "备份的表:"
echo "  - sync_task_config (数据同步任务配置)"
echo "  - etl_task_config (ETL任务配置)"
echo "  - factor_metadata (因子元数据)"
echo "======================================"
