/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Health
     * @description 存活检查 - 进程是否在运行
     */
    get: operations["health_health_get"];
  };
  "/ready": {
    /**
     * Ready
     * @description 就绪检查 - 依赖服务是否可用
     */
    get: operations["ready_ready_get"];
  };
  "/metrics": {
    /**
     * Metrics
     * @description Prometheus 指标端点
     */
    get: operations["metrics_metrics_get"];
  };
  "/api/v1/data/stocks": {
    /**
     * List Stocks
     * @description 获取股票列表
     *
     * 返回所有股票的基本信息（代码、名称、上市日期等）
     */
    get: operations["list_stocks_api_v1_data_stocks_get"];
  };
  "/api/v1/data/daily": {
    /**
     * Get Daily
     * @description 获取日线数据
     *
     * - **ts_code**: 股票代码（可选）
     * - **start_date**: 开始日期 YYYYMMDD（可选）
     * - **end_date**: 结束日期 YYYYMMDD（可选）
     * - **limit**: 返回记录数限制（最大 10000）
     *
     * 注意：查询 sync_daily_data 表（包含完整 OHLCV 数据）
     */
    get: operations["get_daily_api_v1_data_daily_get"];
  };
  "/api/v1/data/tables/{table_name}/info": {
    /**
     * Get Table Info
     * @description 获取表信息
     *
     * 返回表的结构信息（列名、类型等）
     */
    get: operations["get_table_info_api_v1_data_tables__table_name__info_get"];
  };
  "/api/v1/data/tables": {
    /**
     * List Tables
     * @description 列出所有表
     *
     * 返回数据库中所有表的列表
     */
    get: operations["list_tables_api_v1_data_tables_get"];
  };
  "/api/v1/factor/analysis/alphalens": {
    /**
     * Submit Analysis
     * @description 提交因子分析任务（异步）。立即返回 task_id，后台执行分析。
     */
    post: operations["submit_analysis_api_v1_factor_analysis_alphalens_post"];
  };
  "/api/v1/factor/analysis/status/{task_id}": {
    /**
     * Get Analysis Status
     * @description 查询分析任务状态
     */
    get: operations["get_analysis_status_api_v1_factor_analysis_status__task_id__get"];
  };
  "/api/v1/factor/analysis/{factor_id}/latest": {
    /**
     * Get Latest Alphalens Analysis
     * @description 获取指定因子的最新 Alphalens 分析结果
     */
    get: operations["get_latest_alphalens_analysis_api_v1_factor_analysis__factor_id__latest_get"];
  };
  "/api/v1/factor/analysis/{factor_id}/detail/{analysis_id}": {
    /**
     * Get Alphalens Analysis By Id
     * @description 按 task_id 获取指定 Alphalens 分析结果
     */
    get: operations["get_alphalens_analysis_by_id_api_v1_factor_analysis__factor_id__detail__analysis_id__get"];
    /**
     * Delete Alphalens Analysis By Id
     * @description 删除指定的 Alphalens 分析结果
     */
    delete: operations["delete_alphalens_analysis_by_id_api_v1_factor_analysis__factor_id__detail__analysis_id__delete"];
  };
  "/api/v1/factor/analysis/trading-days": {
    /**
     * Get Trading Days
     * @description 获取指定范围内的交易日列表（YYYYMMDD 格式）
     */
    get: operations["get_trading_days_api_v1_factor_analysis_trading_days_get"];
  };
  "/api/v1/factor/run": {
    /**
     * Run Production
     * @description 运行生产任务（异步）
     *
     * 立即返回 run_id，后台执行计算。使用 /production/status/{run_id} 查询状态。
     */
    post: operations["run_production_api_v1_factor_run_post"];
  };
  "/api/v1/factor/batch-run": {
    /**
     * Batch Run Production
     * @description 批量计算因子（异步）
     *
     * 立即返回所有 run_id，后台并行执行。使用 /production/status/{run_id} 查询各因子状态。
     */
    post: operations["batch_run_production_api_v1_factor_batch_run_post"];
  };
  "/api/v1/factor/factors/test": {
    /**
     * Test Factor Code
     * @description 编译并测试因子代码，返回计算结果预览
     *
     * 流程：
     * 1. 编译代码，提取 compute 函数（通过 @factor 装饰器或直接定义）
     * 2. 加载指定日期范围的真实数据
     * 3. 执行因子计算
     * 4. 返回结果预览（含统计信息）
     */
    post: operations["test_factor_code_api_v1_factor_factors_test_post"];
  };
  "/api/v1/factor/factors": {
    /**
     * List Registered Factors
     * @description 列出所有因子（从 PostgreSQL factor_configs + DolphinDB factor_values 最新日期）
     */
    get: operations["list_registered_factors_api_v1_factor_factors_get"];
    /**
     * Create Factor
     * @description 创建新因子（写入 PostgreSQL factor_configs）
     */
    post: operations["create_factor_api_v1_factor_factors_post"];
  };
  "/api/v1/factor/factors/{factor_id}": {
    /**
     * Update Factor
     * @description 更新因子元数据（PostgreSQL factor_configs）
     */
    put: operations["update_factor_api_v1_factor_factors__factor_id__put"];
    /**
     * Delete Factor
     * @description 删除因子元数据，可选删除因子值数据
     */
    delete: operations["delete_factor_api_v1_factor_factors__factor_id__delete"];
  };
  "/api/v1/factor/factors/{factor_id}/code": {
    /**
     * Get Factor Code
     * @description 获取因子源代码（从 PostgreSQL factor_configs 读取）
     */
    get: operations["get_factor_code_api_v1_factor_factors__factor_id__code_get"];
    /**
     * Update Factor Code
     * @description 更新因子源代码（保存到 PostgreSQL factor_configs）
     */
    put: operations["update_factor_code_api_v1_factor_factors__factor_id__code_put"];
  };
  "/api/v1/factor/factors/{factor_id}/data": {
    /**
     * Get Factor Data
     * @description 查询因子值数据（DolphinDB factor_values，时序数据）
     */
    get: operations["get_factor_data_api_v1_factor_factors__factor_id__data_get"];
  };
  "/api/v1/factor/factors/{factor_id}/stats": {
    /**
     * Get Factor Stats
     * @description 获取因子统计摘要（DolphinDB factor_values，时序数据）
     */
    get: operations["get_factor_stats_api_v1_factor_factors__factor_id__stats_get"];
  };
  "/api/v1/flows": {
    /**
     * List Flows
     * @description List all flow configurations
     */
    get: operations["list_flows_api_v1_flows_get"];
    /**
     * Create Flow
     * @description Create a new flow configuration
     */
    post: operations["create_flow_api_v1_flows_post"];
  };
  "/api/v1/flows/{name}": {
    /**
     * Get Flow
     * @description Get a single flow configuration
     */
    get: operations["get_flow_api_v1_flows__name__get"];
    /**
     * Update Flow
     * @description Update a flow configuration
     */
    put: operations["update_flow_api_v1_flows__name__put"];
    /**
     * Delete Flow
     * @description Delete a flow (disable by default, or hard delete)
     */
    delete: operations["delete_flow_api_v1_flows__name__delete"];
  };
  "/api/v1/flows/{name}/backfill": {
    /**
     * Backfill Flow
     * @description 回溯模式：按交易日串行触发多个 FlowRun（后台执行）
     */
    post: operations["backfill_flow_api_v1_flows__name__backfill_post"];
  };
  "/api/v1/flows/{name}/runs/{flow_run_id}": {
    /**
     * Get Flow Run Detail
     * @description 获取单次 flow_run 的详情（flow_run_id 为随机 run_id 字符串）
     */
    get: operations["get_flow_run_detail_api_v1_flows__name__runs__flow_run_id__get"];
  };
  "/api/v1/flows/{name}/runs": {
    /**
     * List Flow Runs
     * @description List flow execution history
     */
    get: operations["list_flow_runs_api_v1_flows__name__runs_get"];
  };
  "/api/v1/flows/infer-dependencies": {
    /**
     * Infer Dependencies
     * @description Infer dependencies for tasks automatically
     *
     * For ETL tasks: parses SQL to find source tables and maps to sync tasks
     * For factor tasks: uses depends_on from factor config
     */
    post: operations["infer_dependencies_api_v1_flows_infer_dependencies_post"];
  };
  "/api/v1/config/field-mappings": {
    /**
     * Get Field Mappings
     * @description 获取所有字段映射配置（PostgreSQL factor_field_mappings）
     */
    get: operations["get_field_mappings_api_v1_config_field_mappings_get"];
    /**
     * Update Field Mappings
     * @description 批量更新字段映射配置（PostgreSQL factor_field_mappings）
     */
    put: operations["update_field_mappings_api_v1_config_field_mappings_put"];
  };
  "/api/v1/config/field-mappings/resolved": {
    /**
     * Get Resolved Field Mappings
     * @description 返回简化的 field_key → source_label 字典，供前端注解显示
     */
    get: operations["get_resolved_field_mappings_api_v1_config_field_mappings_resolved_get"];
  };
  "/api/v1/config/table-columns/{table_name}": {
    /**
     * Get Table Columns
     * @description 获取指定 DolphinDB 表的列名列表
     */
    get: operations["get_table_columns_api_v1_config_table_columns__table_name__get"];
  };
  "/api/v1/config/available-tables": {
    /**
     * Get Available Tables
     * @description 获取所有可用的数据表（sync/etl/factor，均从 PostgreSQL 查询）
     */
    get: operations["get_available_tables_api_v1_config_available_tables_get"];
  };
  "/api/v1/config/index/available": {
    /**
     * List Available Indices
     * @description 查询可订阅的指数列表，支持搜索、筛选和分页
     */
    get: operations["list_available_indices_api_v1_config_index_available_get"];
  };
  "/api/v1/config/index/subscribe": {
    /**
     * Subscribe Index
     * @description 订阅指数：创建同步任务并建表
     */
    post: operations["subscribe_index_api_v1_config_index_subscribe_post"];
  };
  "/api/v1/config/index/subscribe/{index_code}": {
    /**
     * Unsubscribe Index
     * @description 取消订阅指数：删除同步任务和数据表
     */
    delete: operations["unsubscribe_index_api_v1_config_index_subscribe__index_code__delete"];
  };
  "/api/v1/config/index/preference": {
    /**
     * Get User Preference
     * @description 获取用户的同步偏好配置
     */
    get: operations["get_user_preference_api_v1_config_index_preference_get"];
    /**
     * Save User Preference
     * @description 保存用户的同步偏好配置
     */
    post: operations["save_user_preference_api_v1_config_index_preference_post"];
  };
  "/api/v1/config/index-pool/list": {
    /**
     * List Index Pools
     * @description 列出所有指数股票池（PostgreSQL index_configs）
     */
    get: operations["list_index_pools_api_v1_config_index_pool_list_get"];
  };
  "/api/v1/config/export": {
    /**
     * Export Configs
     * @description 导出配置
     *
     * Args:
     *     request: 导出请求
     *
     * Returns:
     *     导出响应
     *
     * Raises:
     *     HTTPException: 导出失败时
     */
    post: operations["export_configs_api_v1_config_export_post"];
  };
  "/api/v1/config/import/verify": {
    /**
     * Verify Import
     * @description 验证导入文件并预览差异
     *
     * Args:
     *     request: 验证请求
     *
     * Returns:
     *     验证响应
     *
     * Raises:
     *     HTTPException: 验证失败时
     */
    post: operations["verify_import_api_v1_config_import_verify_post"];
  };
  "/api/v1/config/import/apply": {
    /**
     * Apply Import
     * @description 执行导入
     *
     * Args:
     *     request: 导入请求
     *
     * Returns:
     *     导入响应
     *
     * Raises:
     *     HTTPException: 导入失败时
     */
    post: operations["apply_import_api_v1_config_import_apply_post"];
  };
  "/api/v1/config/types": {
    /**
     * Get Config Types
     * @description 获取可用的配置类型列表（新旧值都包含，向后兼容）
     *
     * Returns:
     *     配置类型列表
     */
    get: operations["get_config_types_api_v1_config_types_get"];
  };
  "/api/v1/tasks/running": {
    /**
     * Get Running Tasks
     * @description 获取所有正在运行的任务（查询 PostgreSQL task_runs 表）
     */
    get: operations["get_running_tasks_api_v1_tasks_running_get"];
  };
  "/api/v1/tasks/history": {
    /**
     * Get Task History
     * @description 获取最近完成/失败的任务历史（查询 PostgreSQL task_runs 表）
     */
    get: operations["get_task_history_api_v1_tasks_history_get"];
  };
  "/api/v1/tasks/cleanup": {
    /**
     * Cleanup Stale Tasks
     * @description 清理僵尸任务（将长时间 running 的记录标记为 failed）
     */
    post: operations["cleanup_stale_tasks_api_v1_tasks_cleanup_post"];
  };
  "/api/v1/tasks/etl/test": {
    /**
     * Test Etl Script
     * @description 测试 ETL 脚本，返回执行结果及字段类型
     */
    post: operations["test_etl_script_api_v1_tasks_etl_test_post"];
  };
  "/api/v1/tasks/etl/{task_id}/create-table": {
    /**
     * Create Etl Table
     * @description 根据字段定义创建 ETL 目标表
     */
    post: operations["create_etl_table_api_v1_tasks_etl__task_id__create_table_post"];
  };
  "/api/v1/tasks/etl/{task_id}/schema": {
    /**
     * Get Etl Table Schema
     * @description 获取 ETL 任务的字段定义
     */
    get: operations["get_etl_table_schema_api_v1_tasks_etl__task_id__schema_get"];
  };
  "/api/v1/tasks/{task_type}/{task_id}/status": {
    /**
     * Get Task Data Status
     * @description 获取任务数据状态（最新数据日期、上次同步时间）
     */
    get: operations["get_task_data_status_api_v1_tasks__task_type___task_id__status_get"];
  };
  "/api/v1/tasks/{task_type}": {
    /**
     * List Tasks
     * @description 列出所有任务
     */
    get: operations["list_tasks_api_v1_tasks__task_type__get"];
    /**
     * Create Task
     * @description 创建新任务
     */
    post: operations["create_task_api_v1_tasks__task_type__post"];
  };
  "/api/v1/tasks/{task_type}/status/{run_id}": {
    /**
     * Get Task Status
     * @description 查询任务执行状态（查询 PostgreSQL task_runs 表）
     */
    get: operations["get_task_status_api_v1_tasks__task_type__status__run_id__get"];
  };
  "/api/v1/tasks/{task_type}/{task_id}": {
    /**
     * Get Task
     * @description 获取单个任务
     */
    get: operations["get_task_api_v1_tasks__task_type___task_id__get"];
    /**
     * Update Task
     * @description 更新任务
     */
    put: operations["update_task_api_v1_tasks__task_type___task_id__put"];
    /**
     * Delete Task
     * @description 删除任务（软删除，设置 enabled=false）
     */
    delete: operations["delete_task_api_v1_tasks__task_type___task_id__delete"];
  };
  "/api/v1/tasks/{task_type}/{task_id}/execute": {
    /**
     * Execute Task
     * @description 执行任务（异步）
     *
     * 立即返回 run_id，后台执行任务。使用 /tasks/{task_type}/status/{run_id} 查询状态。
     */
    post: operations["execute_task_api_v1_tasks__task_type___task_id__execute_post"];
  };
  "/api/v1/tasks/{task_type}/{task_id}/inspect": {
    /**
     * Inspect Task Data
     * @description 数据探查：检查任务表的数据完整性
     *
     * 返回：
     * - 表的存在性
     * - 数据日期范围（最早/最晚日期）
     * - 实际数据天数 vs 预期交易日天数
     * - 缺失的交易日列表
     * - 数据覆盖率
     */
    get: operations["inspect_task_data_api_v1_tasks__task_type___task_id__inspect_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AnalysisRequest */
    AnalysisRequest: {
      /** Factor Id */
      factor_id: string;
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Periods
       * @default [
       *   1,
       *   5,
       *   10
       * ]
       */
      periods?: number[];
      /**
       * Quantiles
       * @default 5
       */
      quantiles?: number;
      /** Index Pool */
      index_pool?: string | null;
      /** Groupby Field */
      groupby_field?: string | null;
      /**
       * Next Day Entry
       * @default true
       */
      next_day_entry?: boolean;
      /**
       * Entry Price
       * @default open
       */
      entry_price?: string;
      /**
       * Neutralize
       * @default false
       */
      neutralize?: boolean;
      /** Neutralize Controls */
      neutralize_controls?: string[] | null;
      /**
       * Industry Level
       * @default industry_l1
       */
      industry_level?: string;
      /**
       * Winsorize
       * @default false
       */
      winsorize?: boolean;
      /**
       * Winsorize Lower
       * @default 0.01
       */
      winsorize_lower?: number;
      /**
       * Winsorize Upper
       * @default 0.99
       */
      winsorize_upper?: number;
    };
    /** BackfillRequest */
    BackfillRequest: {
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
    };
    /**
     * BatchRunRequest
     * @description 批量运行请求
     */
    BatchRunRequest: {
      /** Factor Ids */
      factor_ids: string[];
      /**
       * Mode
       * @default incremental
       */
      mode?: string;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      preprocess?: components["schemas"]["PreprocessOptions"] | null;
    };
    /** ConfigItemDiff */
    ConfigItemDiff: {
      /**
       * Item Id
       * @description 配置项 ID
       */
      item_id: string;
      /**
       * Status
       * @description 状态: new/modified/unchanged/deleted
       */
      status: string;
      /**
       * Current
       * @description 当前配置（如存在）
       */
      current?: {
        [key: string]: unknown;
      } | null;
      /**
       * Imported
       * @description 导入配置（如存在）
       */
      imported?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ConfigType
     * @enum {string}
     */
    ConfigType: "sync_tasks" | "etl_tasks" | "factor_configs" | "factor_field_mappings" | "flow_configs";
    /** ConfigTypeDiff */
    ConfigTypeDiff: {
      /** @description 配置类型 */
      config_type: components["schemas"]["ConfigType"];
      /**
       * Items
       * @description 配置项差异列表
       */
      items?: components["schemas"]["ConfigItemDiff"][];
      /**
       * Summary
       * @description 统计: new/modified/unchanged/deleted
       */
      summary?: {
        [key: string]: number;
      };
    };
    /** DataConfigUpdateRequest */
    DataConfigUpdateRequest: {
      /** Mappings */
      mappings: components["schemas"]["DataFieldMapping"][];
    };
    /** DataFieldMapping */
    DataFieldMapping: {
      /** Field Key */
      field_key: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Table Name
       * @default
       */
      table_name?: string;
      /**
       * Column Name
       * @default
       */
      column_name?: string;
      /**
       * Extra Config
       * @default {}
       */
      extra_config?: string;
    };
    /**
     * DataInspectionResponse
     * @description 数据探查响应
     */
    DataInspectionResponse: {
      /** Table Name */
      table_name: string;
      /** Exists */
      exists: boolean;
      /** Has Data */
      has_data?: boolean | null;
      /** Date Field */
      date_field?: string | null;
      /** Min Date */
      min_date?: string | null;
      /** Max Date */
      max_date?: string | null;
      /** Actual Dates */
      actual_dates?: number | null;
      /** Expected Dates */
      expected_dates?: number | null;
      /** Missing Dates */
      missing_dates?: string[] | null;
      /** Missing Count */
      missing_count?: number | null;
      /** Coverage Percent */
      coverage_percent?: number | null;
      /** Trading Calendar Available */
      trading_calendar_available?: boolean | null;
      /** Message */
      message?: string | null;
    };
    /**
     * DeleteResponse
     * @description 删除响应
     */
    DeleteResponse: {
      /** Success */
      success: boolean;
      /** Message */
      message: string;
      /** Task Id */
      task_id: string;
      /** Task Type */
      task_type: string;
    };
    /** ExportRequest */
    ExportRequest: {
      /**
       * Config Types
       * @description 要导出的配置类型列表
       */
      config_types: components["schemas"]["ConfigType"][];
    };
    /** ExportResponse */
    ExportResponse: {
      /**
       * Filename
       * @description 导出文件名
       */
      filename: string;
      /**
       * Content
       * @description Base64 编码的 JSON 内容
       */
      content: string;
    };
    /** FactorCodeUpdateRequest */
    FactorCodeUpdateRequest: {
      /** Filename */
      filename: string;
      /** Code */
      code: string;
    };
    /** FactorCreateRequest */
    FactorCreateRequest: {
      /** Factor Id */
      factor_id: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Category
       * @default custom
       */
      category?: string;
      /**
       * Compute Mode
       * @default incremental
       */
      compute_mode?: string;
      /**
       * Depends On
       * @default []
       */
      depends_on?: string[];
      /**
       * Storage Target
       * @default factor_values
       */
      storage_target?: string;
      /**
       * Params
       * @default {}
       */
      params?: {
        [key: string]: unknown;
      };
      /** Code */
      code?: string | null;
      /**
       * Align Calendar
       * @default false
       */
      align_calendar?: boolean;
    };
    /**
     * FactorTestRequest
     * @description 因子测试请求
     */
    FactorTestRequest: {
      /** Code */
      code: string;
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Params
       * @default {}
       */
      params?: {
        [key: string]: unknown;
      };
      /**
       * Depends On
       * @default [
       *   "sync_daily_data"
       * ]
       */
      depends_on?: string[];
      /** Preprocess */
      preprocess?: {
        [key: string]: unknown;
      } | null;
      /**
       * Lookback Days
       * @default 60
       */
      lookback_days?: number;
    };
    /** FactorUpdateRequest */
    FactorUpdateRequest: {
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /** Compute Mode */
      compute_mode?: string | null;
      /** Depends On */
      depends_on?: string[] | null;
      /** Storage Target */
      storage_target?: string | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      } | null;
      /** Align Calendar */
      align_calendar?: boolean | null;
    };
    /**
     * FilterFieldConfig
     * @description 单个筛选字段配置
     */
    FilterFieldConfig: {
      /**
       * Field
       * @description 字段名
       */
      field: string;
      /**
       * Label
       * @description 显示标签
       */
      label: string;
      /**
       * Enabled
       * @description 是否启用为筛选项
       * @default true
       */
      enabled?: boolean;
      /**
       * Default Value
       * @description 默认筛选值
       */
      default_value?: string | null;
    };
    /**
     * FlowConfigCreate
     * @description Create Flow Configuration
     */
    FlowConfigCreate: {
      /**
       * Name
       * @description Flow name (unique)
       */
      name: string;
      /**
       * Description
       * @description Flow description
       * @default
       */
      description?: string;
      /**
       * Cron
       * @description Cron expression (empty = manual only)
       */
      cron?: string | null;
      /**
       * Tags
       * @description Tags
       */
      tags?: string[];
      /**
       * Enabled
       * @description Whether flow is enabled
       * @default true
       */
      enabled?: boolean;
      /**
       * Date Offset Days
       * @description Date offset: -1=yesterday, 0=today, 1=tomorrow
       * @default 0
       */
      date_offset_days?: number;
      /**
       * Tasks
       * @description Tasks in DAG
       */
      tasks?: components["schemas"]["TaskInDAG"][];
    };
    /**
     * FlowConfigInDB
     * @description Flow Configuration from Database
     */
    FlowConfigInDB: {
      /**
       * Name
       * @description Flow name (unique)
       */
      name: string;
      /**
       * Description
       * @description Flow description
       * @default
       */
      description?: string;
      /**
       * Cron
       * @description Cron expression (empty = manual only)
       */
      cron?: string | null;
      /**
       * Tags
       * @description Tags
       */
      tags?: string[];
      /**
       * Enabled
       * @description Whether flow is enabled
       * @default true
       */
      enabled?: boolean;
      /**
       * Date Offset Days
       * @description Date offset: -1=yesterday, 0=today, 1=tomorrow
       * @default 0
       */
      date_offset_days?: number;
      /**
       * Tasks
       * @description Tasks in DAG
       */
      tasks?: components["schemas"]["TaskInDAG"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /**
     * FlowConfigListItem
     * @description Flow Configuration for List View
     */
    FlowConfigListItem: {
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Cron */
      cron: string;
      /** Tags */
      tags: string[];
      /** Enabled */
      enabled: boolean;
      /** Date Offset Days */
      date_offset_days: number;
      /** Task Count */
      task_count: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * FlowConfigUpdate
     * @description Update Flow Configuration
     */
    FlowConfigUpdate: {
      /** Description */
      description?: string | null;
      /** Cron */
      cron?: string | null;
      /** Tags */
      tags?: string[] | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Date Offset Days */
      date_offset_days?: number | null;
      /** Tasks */
      tasks?: components["schemas"]["TaskInDAG"][] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImportApplyRequest */
    ImportApplyRequest: {
      /**
       * Content
       * @description Base64 编码的 JSON 内容
       */
      content: string;
      /** @description 导入模式 */
      mode: components["schemas"]["ImportMode"];
      /**
       * Selections
       * @description 选中的配置项 ID 列表
       */
      selections?: {
        [key: string]: string[];
      } | null;
    };
    /** ImportApplyResponse */
    ImportApplyResponse: {
      /**
       * Success
       * @description 是否成功
       */
      success: boolean;
      /**
       * Summary
       * @description 各类型导入结果统计
       */
      summary?: {
        [key: string]: components["schemas"]["ImportResultSummary"];
      };
      /**
       * Errors
       * @description 错误列表
       */
      errors?: string[];
    };
    /**
     * ImportMode
     * @enum {string}
     */
    ImportMode: "fast" | "safe";
    /** ImportResultSummary */
    ImportResultSummary: {
      /**
       * Created
       * @description 新创建数量
       * @default 0
       */
      created?: number;
      /**
       * Updated
       * @description 更新数量
       * @default 0
       */
      updated?: number;
      /**
       * Skipped
       * @description 跳过数量
       * @default 0
       */
      skipped?: number;
    };
    /** ImportVerifyRequest */
    ImportVerifyRequest: {
      /**
       * Content
       * @description Base64 编码的 JSON 内容
       */
      content: string;
      /** @description 导入模式 */
      mode: components["schemas"]["ImportMode"];
    };
    /** ImportVerifyResponse */
    ImportVerifyResponse: {
      /**
       * Valid
       * @description 是否验证通过
       */
      valid: boolean;
      /**
       * Errors
       * @description 错误列表
       */
      errors?: string[];
      /**
       * Diffs
       * @description 差异预览（安全模式）
       */
      diffs?: components["schemas"]["ConfigTypeDiff"][] | null;
    };
    /**
     * IndexBasicInfo
     * @description 指数基础信息
     */
    IndexBasicInfo: {
      /** Ts Code */
      ts_code: string;
      /** Name */
      name: string;
      /** Market */
      market: string;
      /** Publisher */
      publisher?: string | null;
      /** List Date */
      list_date?: string | null;
      /** Weight Rule */
      weight_rule?: string | null;
      /** Desc */
      desc?: string | null;
      /** Exp Date */
      exp_date?: string | null;
      /**
       * Is Subscribed
       * @default false
       */
      is_subscribed?: boolean;
      /** Subscribed Task Id */
      subscribed_task_id?: string | null;
    };
    /**
     * IndexListResponse
     * @description 指数列表响应
     */
    IndexListResponse: {
      /** Indices */
      indices: components["schemas"]["IndexBasicInfo"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Limit */
      limit: number;
    };
    /**
     * IndexSubscribeRequest
     * @description 指数订阅请求
     */
    IndexSubscribeRequest: {
      /**
       * Index Code
       * @description 指数代码，如 000001.SH
       */
      index_code: string;
    };
    /**
     * IndexSubscribeResponse
     * @description 指数订阅响应
     */
    IndexSubscribeResponse: {
      /** Task Id */
      task_id: string;
      /** Index Code */
      index_code: string;
      /** Table Name */
      table_name: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /**
     * IndexUnsubscribeResponse
     * @description 指数取消订阅响应
     */
    IndexUnsubscribeResponse: {
      /** Index Code */
      index_code: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /**
     * PreprocessOptions
     * @description 因子计算预处理选项
     */
    PreprocessOptions: {
      /**
       * Adjust Price
       * @default forward
       */
      adjust_price?: string;
      /**
       * Filter St
       * @default true
       */
      filter_st?: boolean;
      /**
       * Filter New Stock
       * @default true
       */
      filter_new_stock?: boolean;
      /**
       * New Stock Days
       * @default 60
       */
      new_stock_days?: number;
      /**
       * Mark Limit
       * @default true
       */
      mark_limit?: boolean;
    };
    /**
     * ProductionRunRequest
     * @description 生产任务运行请求
     */
    ProductionRunRequest: {
      /** Factor Id */
      factor_id: string;
      /**
       * Mode
       * @default incremental
       */
      mode?: string;
      /** Target Date */
      target_date?: string | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      preprocess?: components["schemas"]["PreprocessOptions"] | null;
    };
    /**
     * RunningTaskResponse
     * @description 正在运行的任务响应
     */
    RunningTaskResponse: {
      /** Tasks */
      tasks: {
          [key: string]: unknown;
        }[];
      /** Total */
      total: number;
    };
    /**
     * TaskCreateRequest
     * @description 创建任务请求
     */
    TaskCreateRequest: {
      /**
       * Config Data
       * @description 任务配置数据
       */
      config_data: {
        [key: string]: unknown;
      };
    };
    /**
     * TaskExecuteRequest
     * @description 执行任务请求
     */
    TaskExecuteRequest: {
      /**
       * Start Date
       * @description 开始日期 (YYYYMMDD)
       */
      start_date?: string | null;
      /**
       * End Date
       * @description 结束日期 (YYYYMMDD)
       */
      end_date?: string | null;
      /**
       * Params
       * @description 执行参数
       */
      params?: {
        [key: string]: unknown;
      };
      /**
       * Flow Run Id
       * @description 关联的 flow_run_id（调度器传入）
       */
      flow_run_id?: number | null;
      /**
       * Run Id
       * @description 预生成的 run_id（调度器传入，用于合并记录）
       */
      run_id?: string | null;
    };
    /**
     * TaskExecuteResponse
     * @description 任务执行响应
     */
    TaskExecuteResponse: {
      /** Status */
      status: string;
      /** Message */
      message: string;
      /** Task Id */
      task_id: string;
      /** Task Type */
      task_type: string;
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * TaskHistoryResponse
     * @description 历史任务响应
     */
    TaskHistoryResponse: {
      /** Tasks */
      tasks: {
          [key: string]: unknown;
        }[];
      /** Total */
      total: number;
    };
    /**
     * TaskInDAG
     * @description Task within a DAG
     */
    TaskInDAG: {
      /**
       * Id
       * @description Task ID (e.g., sync_daily, factor_ma_20)
       */
      id: string;
      /**
       * Type
       * @description Task type: sync, etl, factor, flow
       */
      type: string;
      /**
       * Depends On
       * @description Dependencies (task IDs)
       */
      depends_on?: string[];
      /**
       * Flow Name
       * @description Flow name (only for type=flow)
       */
      flow_name?: string | null;
    };
    /**
     * TaskListResponse
     * @description 任务列表响应
     */
    TaskListResponse: {
      /** Tasks */
      tasks: {
          [key: string]: unknown;
        }[];
      /** Total */
      total: number;
      /** Task Type */
      task_type: string;
    };
    /**
     * TaskResponse
     * @description 单个任务响应
     */
    TaskResponse: {
      /** Task */
      task: {
        [key: string]: unknown;
      };
      /** Task Type */
      task_type: string;
    };
    /**
     * TaskUpdateRequest
     * @description 更新任务请求
     */
    TaskUpdateRequest: {
      /**
       * Config Data
       * @description 更新的配置数据
       */
      config_data: {
        [key: string]: unknown;
      };
    };
    /**
     * UserSyncPreference
     * @description 用户同步偏好配置
     */
    UserSyncPreference: {
      /**
       * Index Basic Table
       * @description 指数基础信息表名
       */
      index_basic_table: string;
      /**
       * Filter Config
       * @description 筛选字段配置
       */
      filter_config?: components["schemas"]["FilterFieldConfig"][] | null;
    };
    /**
     * UserSyncPreferenceResponse
     * @description 用户同步偏好响应
     */
    UserSyncPreferenceResponse: {
      /** User Id */
      user_id: string;
      /** Index Basic Table */
      index_basic_table: string;
      /** Filter Config */
      filter_config?: components["schemas"]["FilterFieldConfig"][] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health
   * @description 存活检查 - 进程是否在运行
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Ready
   * @description 就绪检查 - 依赖服务是否可用
   */
  ready_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Metrics
   * @description Prometheus 指标端点
   */
  metrics_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Stocks
   * @description 获取股票列表
   *
   * 返回所有股票的基本信息（代码、名称、上市日期等）
   */
  list_stocks_api_v1_data_stocks_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Get Daily
   * @description 获取日线数据
   *
   * - **ts_code**: 股票代码（可选）
   * - **start_date**: 开始日期 YYYYMMDD（可选）
   * - **end_date**: 结束日期 YYYYMMDD（可选）
   * - **limit**: 返回记录数限制（最大 10000）
   *
   * 注意：查询 sync_daily_data 表（包含完整 OHLCV 数据）
   */
  get_daily_api_v1_data_daily_get: {
    parameters: {
      query?: {
        /** @description 股票代码 */
        ts_code?: string | null;
        /** @description 开始日期 YYYYMMDD */
        start_date?: string | null;
        /** @description 结束日期 YYYYMMDD */
        end_date?: string | null;
        /** @description 返回记录数限制 */
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Table Info
   * @description 获取表信息
   *
   * 返回表的结构信息（列名、类型等）
   */
  get_table_info_api_v1_data_tables__table_name__info_get: {
    parameters: {
      path: {
        table_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Tables
   * @description 列出所有表
   *
   * 返回数据库中所有表的列表
   */
  list_tables_api_v1_data_tables_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Submit Analysis
   * @description 提交因子分析任务（异步）。立即返回 task_id，后台执行分析。
   */
  submit_analysis_api_v1_factor_analysis_alphalens_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Analysis Status
   * @description 查询分析任务状态
   */
  get_analysis_status_api_v1_factor_analysis_status__task_id__get: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Latest Alphalens Analysis
   * @description 获取指定因子的最新 Alphalens 分析结果
   */
  get_latest_alphalens_analysis_api_v1_factor_analysis__factor_id__latest_get: {
    parameters: {
      path: {
        factor_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Alphalens Analysis By Id
   * @description 按 task_id 获取指定 Alphalens 分析结果
   */
  get_alphalens_analysis_by_id_api_v1_factor_analysis__factor_id__detail__analysis_id__get: {
    parameters: {
      path: {
        factor_id: string;
        analysis_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Alphalens Analysis By Id
   * @description 删除指定的 Alphalens 分析结果
   */
  delete_alphalens_analysis_by_id_api_v1_factor_analysis__factor_id__detail__analysis_id__delete: {
    parameters: {
      path: {
        factor_id: string;
        analysis_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Trading Days
   * @description 获取指定范围内的交易日列表（YYYYMMDD 格式）
   */
  get_trading_days_api_v1_factor_analysis_trading_days_get: {
    parameters: {
      query: {
        start: string;
        end: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Run Production
   * @description 运行生产任务（异步）
   *
   * 立即返回 run_id，后台执行计算。使用 /production/status/{run_id} 查询状态。
   */
  run_production_api_v1_factor_run_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductionRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Batch Run Production
   * @description 批量计算因子（异步）
   *
   * 立即返回所有 run_id，后台并行执行。使用 /production/status/{run_id} 查询各因子状态。
   */
  batch_run_production_api_v1_factor_batch_run_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Test Factor Code
   * @description 编译并测试因子代码，返回计算结果预览
   *
   * 流程：
   * 1. 编译代码，提取 compute 函数（通过 @factor 装饰器或直接定义）
   * 2. 加载指定日期范围的真实数据
   * 3. 执行因子计算
   * 4. 返回结果预览（含统计信息）
   */
  test_factor_code_api_v1_factor_factors_test_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FactorTestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Registered Factors
   * @description 列出所有因子（从 PostgreSQL factor_configs + DolphinDB factor_values 最新日期）
   */
  list_registered_factors_api_v1_factor_factors_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Create Factor
   * @description 创建新因子（写入 PostgreSQL factor_configs）
   */
  create_factor_api_v1_factor_factors_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FactorCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Factor
   * @description 更新因子元数据（PostgreSQL factor_configs）
   */
  update_factor_api_v1_factor_factors__factor_id__put: {
    parameters: {
      path: {
        factor_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FactorUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Factor
   * @description 删除因子元数据，可选删除因子值数据
   */
  delete_factor_api_v1_factor_factors__factor_id__delete: {
    parameters: {
      query?: {
        delete_data?: boolean;
      };
      path: {
        factor_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Factor Code
   * @description 获取因子源代码（从 PostgreSQL factor_configs 读取）
   */
  get_factor_code_api_v1_factor_factors__factor_id__code_get: {
    parameters: {
      path: {
        factor_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Factor Code
   * @description 更新因子源代码（保存到 PostgreSQL factor_configs）
   */
  update_factor_code_api_v1_factor_factors__factor_id__code_put: {
    parameters: {
      path: {
        factor_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FactorCodeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Factor Data
   * @description 查询因子值数据（DolphinDB factor_values，时序数据）
   */
  get_factor_data_api_v1_factor_factors__factor_id__data_get: {
    parameters: {
      query?: {
        start_date?: string | null;
        end_date?: string | null;
        ts_code?: string | null;
        limit?: number;
      };
      path: {
        factor_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Factor Stats
   * @description 获取因子统计摘要（DolphinDB factor_values，时序数据）
   */
  get_factor_stats_api_v1_factor_factors__factor_id__stats_get: {
    parameters: {
      path: {
        factor_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Flows
   * @description List all flow configurations
   */
  list_flows_api_v1_flows_get: {
    parameters: {
      query?: {
        /** @description Only return enabled flows */
        enabled_only?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FlowConfigListItem"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Flow
   * @description Create a new flow configuration
   */
  create_flow_api_v1_flows_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FlowConfigCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FlowConfigInDB"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Flow
   * @description Get a single flow configuration
   */
  get_flow_api_v1_flows__name__get: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FlowConfigInDB"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Flow
   * @description Update a flow configuration
   */
  update_flow_api_v1_flows__name__put: {
    parameters: {
      path: {
        name: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FlowConfigUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FlowConfigInDB"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Flow
   * @description Delete a flow (disable by default, or hard delete)
   */
  delete_flow_api_v1_flows__name__delete: {
    parameters: {
      query?: {
        /** @description Hard delete (permanently remove) */
        hard?: boolean;
      };
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Backfill Flow
   * @description 回溯模式：按交易日串行触发多个 FlowRun（后台执行）
   */
  backfill_flow_api_v1_flows__name__backfill_post: {
    parameters: {
      path: {
        name: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BackfillRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Flow Run Detail
   * @description 获取单次 flow_run 的详情（flow_run_id 为随机 run_id 字符串）
   */
  get_flow_run_detail_api_v1_flows__name__runs__flow_run_id__get: {
    parameters: {
      path: {
        name: string;
        flow_run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Flow Runs
   * @description List flow execution history
   */
  list_flow_runs_api_v1_flows__name__runs_get: {
    parameters: {
      query?: {
        /** @description Maximum number of runs to return */
        limit?: number;
      };
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Infer Dependencies
   * @description Infer dependencies for tasks automatically
   *
   * For ETL tasks: parses SQL to find source tables and maps to sync tasks
   * For factor tasks: uses depends_on from factor config
   */
  infer_dependencies_api_v1_flows_infer_dependencies_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskInDAG"][];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Field Mappings
   * @description 获取所有字段映射配置（PostgreSQL factor_field_mappings）
   */
  get_field_mappings_api_v1_config_field_mappings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Update Field Mappings
   * @description 批量更新字段映射配置（PostgreSQL factor_field_mappings）
   */
  update_field_mappings_api_v1_config_field_mappings_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataConfigUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Resolved Field Mappings
   * @description 返回简化的 field_key → source_label 字典，供前端注解显示
   */
  get_resolved_field_mappings_api_v1_config_field_mappings_resolved_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Get Table Columns
   * @description 获取指定 DolphinDB 表的列名列表
   */
  get_table_columns_api_v1_config_table_columns__table_name__get: {
    parameters: {
      path: {
        table_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Available Tables
   * @description 获取所有可用的数据表（sync/etl/factor，均从 PostgreSQL 查询）
   */
  get_available_tables_api_v1_config_available_tables_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Available Indices
   * @description 查询可订阅的指数列表，支持搜索、筛选和分页
   */
  list_available_indices_api_v1_config_index_available_get: {
    parameters: {
      query?: {
        /** @description 搜索关键词（指数名称或代码） */
        search?: string | null;
        /** @description JSON格式筛选条件，如 {"market":"SSE"} */
        filters?: string | null;
        /** @description 页码 */
        page?: number;
        /** @description 每页数量 */
        limit?: number;
        /** @description 仅显示已订阅的指数 */
        show_subscribed_only?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IndexListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Subscribe Index
   * @description 订阅指数：创建同步任务并建表
   */
  subscribe_index_api_v1_config_index_subscribe_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["IndexSubscribeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IndexSubscribeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Unsubscribe Index
   * @description 取消订阅指数：删除同步任务和数据表
   */
  unsubscribe_index_api_v1_config_index_subscribe__index_code__delete: {
    parameters: {
      path: {
        index_code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IndexUnsubscribeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get User Preference
   * @description 获取用户的同步偏好配置
   */
  get_user_preference_api_v1_config_index_preference_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserSyncPreferenceResponse"];
        };
      };
    };
  };
  /**
   * Save User Preference
   * @description 保存用户的同步偏好配置
   */
  save_user_preference_api_v1_config_index_preference_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSyncPreference"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserSyncPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Index Pools
   * @description 列出所有指数股票池（PostgreSQL index_configs）
   */
  list_index_pools_api_v1_config_index_pool_list_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Export Configs
   * @description 导出配置
   *
   * Args:
   *     request: 导出请求
   *
   * Returns:
   *     导出响应
   *
   * Raises:
   *     HTTPException: 导出失败时
   */
  export_configs_api_v1_config_export_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Verify Import
   * @description 验证导入文件并预览差异
   *
   * Args:
   *     request: 验证请求
   *
   * Returns:
   *     验证响应
   *
   * Raises:
   *     HTTPException: 验证失败时
   */
  verify_import_api_v1_config_import_verify_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportVerifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ImportVerifyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Apply Import
   * @description 执行导入
   *
   * Args:
   *     request: 导入请求
   *
   * Returns:
   *     导入响应
   *
   * Raises:
   *     HTTPException: 导入失败时
   */
  apply_import_api_v1_config_import_apply_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ImportApplyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Config Types
   * @description 获取可用的配置类型列表（新旧值都包含，向后兼容）
   *
   * Returns:
   *     配置类型列表
   */
  get_config_types_api_v1_config_types_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: string;
            }[];
        };
      };
    };
  };
  /**
   * Get Running Tasks
   * @description 获取所有正在运行的任务（查询 PostgreSQL task_runs 表）
   */
  get_running_tasks_api_v1_tasks_running_get: {
    parameters: {
      query?: {
        /** @description 按任务类型过滤 (sync/etl/factor) */
        task_type?: string | null;
        /** @description 按任务ID过滤 */
        task_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunningTaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Task History
   * @description 获取最近完成/失败的任务历史（查询 PostgreSQL task_runs 表）
   */
  get_task_history_api_v1_tasks_history_get: {
    parameters: {
      query?: {
        limit?: number;
        /** @description 按任务类型过滤 (sync/etl/factor) */
        task_type?: string | null;
        /** @description 按任务ID过滤 */
        task_id?: string | null;
        /** @description 开始日期 (YYYYMMDD)，按 started_at 过滤 */
        start_date?: string | null;
        /** @description 结束日期 (YYYYMMDD)，按 started_at 过滤 */
        end_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskHistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cleanup Stale Tasks
   * @description 清理僵尸任务（将长时间 running 的记录标记为 failed）
   */
  cleanup_stale_tasks_api_v1_tasks_cleanup_post: {
    parameters: {
      query?: {
        /** @description 超时分钟数，0=清理所有running */
        timeout_minutes?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Test Etl Script
   * @description 测试 ETL 脚本，返回执行结果及字段类型
   */
  test_etl_script_api_v1_tasks_etl_test_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Etl Table
   * @description 根据字段定义创建 ETL 目标表
   */
  create_etl_table_api_v1_tasks_etl__task_id__create_table_post: {
    parameters: {
      path: {
        /** @description 任务ID */
        task_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Etl Table Schema
   * @description 获取 ETL 任务的字段定义
   */
  get_etl_table_schema_api_v1_tasks_etl__task_id__schema_get: {
    parameters: {
      path: {
        /** @description 任务ID */
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Task Data Status
   * @description 获取任务数据状态（最新数据日期、上次同步时间）
   */
  get_task_data_status_api_v1_tasks__task_type___task_id__status_get: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl */
        task_type: string;
        /** @description 任务ID */
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Tasks
   * @description 列出所有任务
   */
  list_tasks_api_v1_tasks__task_type__get: {
    parameters: {
      query?: {
        /** @description 是否只返回启用的任务 */
        enabled_only?: boolean;
      };
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Task
   * @description 创建新任务
   */
  create_task_api_v1_tasks__task_type__post: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TaskCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Task Status
   * @description 查询任务执行状态（查询 PostgreSQL task_runs 表）
   */
  get_task_status_api_v1_tasks__task_type__status__run_id__get: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
        /** @description 运行ID */
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Task
   * @description 获取单个任务
   */
  get_task_api_v1_tasks__task_type___task_id__get: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
        /** @description 任务ID */
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Task
   * @description 更新任务
   */
  update_task_api_v1_tasks__task_type___task_id__put: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
        /** @description 任务ID */
        task_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TaskUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Task
   * @description 删除任务（软删除，设置 enabled=false）
   */
  delete_task_api_v1_tasks__task_type___task_id__delete: {
    parameters: {
      query?: {
        /** @description 是否删除关联表 */
        drop_table?: boolean;
      };
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
        /** @description 任务ID */
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Execute Task
   * @description 执行任务（异步）
   *
   * 立即返回 run_id，后台执行任务。使用 /tasks/{task_type}/status/{run_id} 查询状态。
   */
  execute_task_api_v1_tasks__task_type___task_id__execute_post: {
    parameters: {
      path: {
        /** @description 任务类型: sync, etl, factor */
        task_type: string;
        /** @description 任务ID */
        task_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TaskExecuteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskExecuteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Inspect Task Data
   * @description 数据探查：检查任务表的数据完整性
   *
   * 返回：
   * - 表的存在性
   * - 数据日期范围（最早/最晚日期）
   * - 实际数据天数 vs 预期交易日天数
   * - 缺失的交易日列表
   * - 数据覆盖率
   */
  inspect_task_data_api_v1_tasks__task_type___task_id__inspect_get: {
    parameters: {
      path: {
        /** @description 任务类型 (sync/etl/factor) */
        task_type: string;
        /** @description 任务 ID */
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DataInspectionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
